# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('image_url', models.URLField(default=django.utils.timezone.now)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
